version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: notes-php-mysql
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=notes
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
